spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/meoipzi
    username: sujung
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

cloud:
  aws:
    credentials:
      accessKey: AKIARBD2KDLFRUIMONGA
      secretKey: 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
    s3:
      bucket: meoipzi
    region:
      static: ap-northeast-2
    stack:
      auto: false
